### ISSUE TITLE
Invalid behavior if user id is UUD

### ISSUE THREAD

**Issue by GamePad64** [aaugustin/django-sesame#17]
Hi! I have my django set up with a custom user model, that uses UUID as user id, but when I try to use sesame, it fails with an exception:

```
Traceback (most recent call last):
  File "/home/gamepad/.local/share/virtualenvs/backend-kGdHPQqo/src/python-telegram-bot/telegram/ext/dispatcher.py", line 301, in process_update
    handler.handle_update(update, self)
  File "/home/gamepad/.local/share/virtualenvs/backend-kGdHPQqo/src/python-telegram-bot/telegram/ext/conversationhandler.py", line 320, in handle_update
    new_state = self.current_handler.handle_update(update, dispatcher)
  File "/home/gamepad/.local/share/virtualenvs/backend-kGdHPQqo/src/python-telegram-bot/telegram/ext/regexhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/mnt/devenv/workspace/mydeposit/backend/tgbot/send_action.py", line 13, in command_func
    return func(bot, update, **kwargs)
  File "/mnt/devenv/workspace/mydeposit/backend/tgbot/auth.py", line 18, in command_func
    return func(bot, update, socialaccount.user, **kwargs)
  File "/mnt/devenv/workspace/mydeposit/backend/tgbot/main.py", line 263, in website_handler
    telegram.InlineKeyboardButton(BTN_WEBSITE, url='https://127.0.0.1/' + sesame.utils.get_query_string(user))
  File "/home/gamepad/.local/share/virtualenvs/backend-kGdHPQqo/lib/python3.6/site-packages/sesame/utils.py", line 21, in get_query_string
    return '?' + urlencode(get_parameters(user))
  File "/home/gamepad/.local/share/virtualenvs/backend-kGdHPQqo/lib/python3.6/site-packages/sesame/utils.py", line 13, in get_parameters
    return {TOKEN_NAME: UrlAuthBackendMixin().create_token(user)}
  File "/home/gamepad/.local/share/virtualenvs/backend-kGdHPQqo/lib/python3.6/site-packages/sesame/backends.py", line 67, in create_token
    return self.sign(struct.pack(str('!i'), user.pk) + h)
struct.error: required argument is not an integer
```
Can you consider custom user id packing scheme?

**Comment by LaundroMat** [comment]
I'm using version ^3.2.1 and ran into the same issue:

```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
..\..\..\.venv\lib\site-packages\sesame\utils.py:47: in get_query_string
    return "?" + urlencode({settings.TOKEN_NAME: create_token(user, scope)})
..\..\..\.venv\lib\site-packages\sesame\tokens.py:16: in create_token
    return tokens.create_token(user, scope)
..\..\..\.venv\lib\site-packages\sesame\tokens_v2.py:133: in create_token
    primary_key = packers.packer.pack_pk(getattr(user, settings.PRIMARY_KEY_FIELD))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'sesame.packers.LongPacker'>
user_pk = UUID('d3b413f6-2249-4daf-92b0-c84d562db011')

    @classmethod
    def pack_pk(cls, user_pk):
>       return struct.pack(cls.fmt, user_pk)
E       struct.error: required argument is not an integer

..\..\..\.venv\lib\site-packages\sesame\packers.py:62: error
```
