### ISSUE TITLE
TypeError: AuthenticationMiddleware() takes no arguments

### ISSUE THREAD

**Issue by roelzkie15** [aaugustin/django-sesame#42]
I wasn't able to integrate this library into my django application after following the [Getting Started](https://github.com/aaugustin/django-sesame#getting-started) section. This is what I get when after following the installation procedure:

```
Traceback (most recent call last):
web_1     |   File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
web_1     |     self.run()
web_1     |   File "/usr/local/lib/python3.7/threading.py", line 865, in run
web_1     |     self._target(*self._args, **self._kwargs)
web_1     |   File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.7/site-packages/django/utils/autoreload.py", line 54, in wrapper
web_1     |     fn(*args, **kwargs)
web_1     |   File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 137, in inner_run
web_1     |     handler = self.get_handler(*args, **options)
web_1     |   File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 27, in get_handler
web_1     |     handler = super().get_handler(*args, **options)
web_1     |   File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 64, in get_handler
web_1     |     return get_internal_wsgi_application()
web_1     |   File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.7/site-packages/django/core/servers/basehttp.py", line 45, in get_internal_wsgi_application
web_1     |     return import_string(app_path)
web_1     |   File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.7/site-packages/django/utils/module_loading.py", line 17, in import_string
web_1     |     module = import_module(module_path)
web_1     |   File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.7/importlib/__init__.py", line 127, in import_module
web_1     |     return _bootstrap._gcd_import(name[level:], package, level)
web_1     |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
web_1     |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
web_1     |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
web_1     |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
web_1     |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
web_1     |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
web_1     |   File "/code/fqpc_api/wsgi.py", line 16, in <module>
web_1     |     application = get_wsgi_application()
web_1     |   File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
web_1     |     return WSGIHandler()
web_1     |   File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.7/site-packages/django/core/handlers/wsgi.py", line 135, in __init__
web_1     |     self.load_middleware()
web_1     |   File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.7/site-packages/django/core/handlers/base.py", line 37, in load_middleware
web_1     |     mw_instance = middleware(handler)
web_1     | TypeError: AuthenticationMiddleware() takes no arguments
```

Does anyone came across this issue? I think this is a bug.

Im using the following stack:
- docker Version 2.0.0.3 (31259)
- pipenv Version 2018.11.26
- django Version 2.2.3
- django-sesame Version 1.0

**Comment by roelzkie15** [comment]
I installed the wrong version **1.0**
