### ISSUE TITLE
Django 1.11 - Sesame 1.3

### ISSUE THREAD

**Issue by yonatancohen** [aaugustin/django-sesame#7]
Hi, so I tried to install the package.
After I added the middleware, my envoriment didn't load, and got the following exception:

```Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_monkey.py", line 589, in __call__
    return self.original_func(*self.args, **self.kwargs)
  File "/Users/yonicohen/Projects/Cleanly_1.11/venv/lib/python2.7/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/Users/yonicohen/Projects/Cleanly_1.11/venv/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 147, in inner_run
    handler = self.get_handler(*args, **options)
  File "/Users/yonicohen/Projects/Cleanly_1.11/venv/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 27, in get_handler
    handler = super(Command, self).get_handler(*args, **options)
  File "/Users/yonicohen/Projects/Cleanly_1.11/venv/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 68, in get_handler
    return get_internal_wsgi_application()
  File "/Users/yonicohen/Projects/Cleanly_1.11/venv/lib/python2.7/site-packages/django/core/servers/basehttp.py", line 47, in get_internal_wsgi_application
    return import_string(app_path)
  File "/Users/yonicohen/Projects/Cleanly_1.11/venv/lib/python2.7/site-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/yonicohen/Projects/Cleanly_1.11/Cleanly/wsgi.py", line 10, in <module>
    application = WSGIHandler()
  File "/Users/yonicohen/Projects/Cleanly_1.11/venv/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 151, in __init__
    self.load_middleware()
  File "/Users/yonicohen/Projects/Cleanly_1.11/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 82, in load_middleware
    mw_instance = middleware(handler)
TypeError: __init__() takes exactly 1 argument (2 given)

**Comment by aaugustin** [comment]
Are you using old-style (MIDDLEWARE_CLASSES) or new-style (MIDDLEWARE) middleware?

If you're using the old style, try sticking with sesame 1.2.

**Comment by yonatancohen** [comment]
I've tried both ways
and both of them didn't worked for me. (new & old)

**Comment by aaugustin** [comment]
I think it's a bug in the way you declare your settings rather than a bug in django-sesame.
